import {normalizeGear} from './equipment-v14.js';
import {CH3_GEAR,CH3_RECIPES,CH3_TRIALS,CH3_LAMPS,CH3_SCHOOLS} from './chapter3-runtime-v14.js';
import {ITEMS,SKILLS} from './data-v14.js';
export function hellFacilityHTML(g,kind,{iconHTML,miniItemIcon,skillDetails,escape,gearIcon}){
 const h=g.ch3||{},button=(label,a,arg='',disabled=false)=>`<button data-hell="${a}" data-hell-arg="${arg}" ${disabled?'disabled':''}>${label}</button>`;
 const cost=c=>Object.entries(c).map(([k,n])=>`${k==='gold'?'金币':ITEMS[k].name} ${n}`).join(' + ');
 const reward=(r,i,action)=>{const gear=CH3_GEAR[r.id],s=ITEMS[r.id]?.skill;return `<article class="mechanism-choice">${r.kind==='bundle'?miniItemIcon('soulAsh'):gear?gearIcon(normalizeGear(gear,g.p.cls)):miniItemIcon(r.id)}<h3>${gear?.name||ITEMS[r.id]?.name||'魂灰 ×4 / 黑曜碎片 ×2'}</h3>${s?`<p>${SKILLS[s].desc}</p>${skillDetails(s)}`:gear?`<p>Lv.${gear.minLevel} · 攻击 +${gear.atk} · 生命 +${gear.hp}</p>`:'<p>供制作使用，不增加永久属性。</p>'}${button('收下这一份',action,i)}</article>`;};
 let title='',body='';
 const unlocked=!!g.flags.ch3HeroRecovered;
 if(kind==='draw'){title='余音教习机 · 魂签轮';body=h.offers?`<p>这份铜页已印好。关闭界面、重新进入或读档，都会保留同一组结果。</p><div class="mechanism-choices">${h.offers.map((r,i)=>reward(r,i,'offer')).join('')}</div>`:`<p>先选研习方向，再从印出的三份物品里选一份。每次至少出现一本尚未学会、行囊也没有的技能书。</p><p class="muted">消耗：${h.freeDraw?'芮妲答应的首次试用，免费':'裂门铜契 ×1 + 魂灰 ×3'} · 已用 ${h.draws||0} / 6 次。只用游戏内材料，无付费抽取。</p>${!unlocked?'<p>先完成救治，机器之后再研究。</p>':''}<div class="mechanism-choices">${Object.entries(CH3_SCHOOLS).map(([k,v])=>`<article class="mechanism-choice"><h3>${{melee:'近身战技',spell:'咒术与魂灯',protectionControl:'防护与控制'}[k]}</h3><p>${v.map(id=>ITEMS[id].name).join(' · ')}</p>${button('印制这个方向','draw',k,!unlocked)}</article>`).join('')}</div>`;}
 if(kind==='forge'){title='芮妲的余温工坊';body=`<p>制作所得放入行囊，不会自动装备。主线的白盐苔与凝晶不作锻造材料。</p><div class="mechanism-choices">${CH3_RECIPES.map(r=>{const id=r.output||r.outputsByClass?.[g.p.cls],name=CH3_GEAR[id]?.name||ITEMS[r.outputItem]?.name,used=h.crafts?.[r.id]||0;return `<article class="mechanism-choice">${CH3_GEAR[id]?gearIcon(normalizeGear(CH3_GEAR[id],g.p.cls)):miniItemIcon(r.outputItem||'cinderIron')}<h3>${name}</h3><p>${cost(r.cost)}</p><p class="muted">本章剩余 ${r.lifetimeLimit-used} 次${r.requires&&!g.flags[r.requires]?' · 需守灯墓室图纸':''}</p>${button('制作','craft',r.id,!unlocked||used>=r.lifetimeLimit||r.requires&&!g.flags[r.requires])}</article>`;}).join('')}</div><h3>拆解备用装备</h3><p class="muted">只拆行囊里的普通装备；身上、独特、剧情纪念装备受保护。每件得 1–3 烬铁屑，按品质计算。</p><div class="row">${g.p.bag.filter(i=>!i.uniqueEffect&&!i.id.startsWith('quest-')&&!i.id.startsWith('ch3-')).map(i=>button('拆解 '+escape(i.name),'dismantle',i.id)).join('')||'没有可拆解的备用装备。'}</div>`;}
 if(kind==='lamp'){title='营地灵灯';body=`<p>灵灯契不占五个战技名额。一次只能保留一种；首次免费，之后在营地花 4 魂灰、30 金更换。改变上限不会补血，也不重置冷却。</p><div class="mechanism-choices">${CH3_LAMPS.map(l=>`<article class="mechanism-choice">${iconHTML(l.id==='warmWick'?'saintAegis':l.id==='sharpWick'?'bloodPact':'echoExchange')}<h3>${l.name}${g.p.lampContract===l.id?' · 已生效':''}</h3><p>${l.description}</p>${button(g.p.lampContract===l.id?'当前契约':'点亮此契','lamp',l.id,!unlocked||g.p.lampContract===l.id)}</article>`).join('')}</div>${!unlocked?'<p>先完成救治，再在营地试灯。</p>':''}`;}
 if(kind==='trial'){title='回声裂隙';body=h.trialReward?`<p>首通奖励，只能领取其中一份。</p><div class="mechanism-choices">${h.trialReward.map((r,i)=>reward(r,i,'trialReward')).join('')}</div>`:`<p>每档两轮短战斗，自备药品。击杀试炼怪不单独掉落；完成后统一结算。首次奖励只领取一次，重复完成得 35 经验、6 金、1 魂灰。</p><div class="mechanism-choices">${CH3_TRIALS.map(t=>`<article class="mechanism-choice"><h3>${{trial1:'残响',trial2:'沉钟',trial3:'锁井'}[t.id]} · 建议 Lv.${t.recommendedLevel}</h3><p>${t.waves.map((w,i)=>'第'+(i+1)+'轮 '+w.length+'只').join(' / ')}<br>普通来袭约 30–37 原始伤害，护盾与减伤另计。</p><p>${h.claims?.[t.id]?'已首通 · 本次只有常规奖励':`首次：${t.firstReward.xp} 经验、${t.firstReward.gold} 金、1 铜契${t.firstReward.memoryThread?'、1 记忆丝':''}，以及装备或书籍二选一。`}</p>${button('开始这档试炼','trial',t.id,!unlocked||h.trial?.active)}</article>`).join('')}</div>${h.trial?.active?button('结束试炼，保留主线物品','trialExit'):''}`;}
 if(kind==='tomb'){title='守灯墓室 · 三道铜闸';body=`<p>铜牌：上闸二刻，中闸归零，下闸一刻。检修时，至少留一盏灯。</p><p>拨动只改变灯轨，不消耗物品。旧柜只开启一次，普通材料可以再次探索取得。</p><div class="mechanism-choices">${[0,1,2].map(i=>`<article class="mechanism-choice">${iconHTML('wispLantern')}<h3>${['上','中','下'][i]}闸 · 刻度 ${h.shutters?.[i]||0}</h3>${button('拨一刻','tomb',i,h.claims?.tomb)}</article>`).join('')}</div>${h.claims?.tomb?'<p>旧柜已开启：走灰短靴、坟钟余震、图纸与材料已收好。</p>':''}`;}
 if(kind==='ferry'){title='修好后的岸灯';body=h.ferryChoice?`<p>镜片可以留在绳结里，也可以带走引灯的铜页。只选一样，岸灯无论如何都会亮起。</p><div class="mechanism-choices"><article class="mechanism-choice"><h3>留灯绳结</h3><p>精神 +2。引魂灯延长 1 秒，每次伤害降低 12%。</p>${button('收下绳结','ferryReward','relic')}</article><article class="mechanism-choice"><h3>《引魂灯》</h3>${skillDetails('wispLantern')}${button('收下铜页','ferryReward','book')}</article></div>`:'<p>岸灯已经亮起。北面盐墙下露出一截侧阶。</p>';}
 if(kind==='boss'){title='狱卒身后的旧匣';body=h.bossChoice?`<p>匣子里留下两样东西，夹在同一根将断的锁销上，只能先护住一样。</p><div class="mechanism-choices"><article class="mechanism-choice"><h3>余烬扣 · 独特遗物</h3><p>生命低于 35% 时受到伤害，获得最大生命 8% 的护盾，持续 3 秒。30 秒内只触发一次。</p>${button('护住余烬扣','bossReward','relic')}</article><article class="mechanism-choice"><h3>《渡客斩》</h3>${skillDetails('ferrymanCut')}${button('护住战技铜页','bossReward','book')}</article></div>`:'<p>物品已经收好，可以乘升降笼继续，也可先回营地。</p>';}
 return `<div class="modal"><section class="panel hell-panel"><header class="panel-head"><h2>${title}</h2><button data-act="resume">返回 ×</button></header><div class="panel-body"><div class="summary"><span>金币 ${g.p.gold}</span><span>魂灰 ${g.p.items.soulAsh||0}</span><span>铜契 ${g.p.items.gateToken||0}</span><span>烬铁 ${g.p.items.cinderIron||0}</span></div>${body}</div></section></div>`;
}
