import {MAPS} from './data-v14.js';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const inside=(p,b)=>!b||(p.x>=b[0]&&p.x<=b[0]+b[2]&&p.y>=b[1]&&p.y<=b[1]+b[3]);
const uniqueEnemy=e=>e.elite||e.isBoss||e.squadLeader||['captain','echo-warden','secret-warden','ch2-bren'].includes(e.id)||e.type==='captain';
const renewableMaps=new Set(['warehouse','road','grove','millpath','bridge','spillway']);
export function migrateMapV9(g,id){const st=g.states[id],m=MAPS[id];if(!st||st.qualityVersion===9)return;for(const a of m.spawns||[]){const key=a[3]||id+'-'+m.spawns.indexOf(a);if(!st.enemies.some(e=>e.id===key))st.enemies.push(g.enemy(a[0],a[1],a[2],key));}for(const e of st.enemies){const fresh=g.enemy(e.type,e.homeX??e.x,e.homeY??e.y,e.id);const ratio=e.hp/Math.max(1,e.maxHP);Object.assign(e,{maxHP:fresh.maxHP,hp:e.dead?0:Math.max(1,Math.round(ratio*fresh.maxHP)),elite:fresh.elite,squadLeader:fresh.squadLeader,aiState:e.dead?'DEAD':'IDLE',returning:false,wind:0,telegraph:null,threat:{},aggroUntil:0});attachGroup(m,e);}st.qualityVersion=9;st.visitCount=st.visitCount||1;}
function attachGroup(m,e){const group=m.encounters?.find(a=>a.spawnIds.includes(e.id));if(group)Object.assign(e,{groupId:group.groupId,leashBounds:group.leashBounds,activationBounds:group.activationBounds,isBossArena:!!group.isBossArena,isBoss:group.bossId===e.id});}
export function refreshVisitV9(g,id,revisiting){const m=MAPS[id],st=g.states[id];if(!revisiting)return;st.visitCount=(st.visitCount||1)+1;if(!renewableMaps.has(id))return;const entries=(m.spawns||[]).map((a,i)=>({a,key:a[3]||id+'-'+i}));for(const {a,key} of entries){const old=st.enemies.find(e=>e.id===key),group=m.encounters?.find(v=>v.spawnIds.includes(key));if(old&&uniqueEnemy(old)||group?.refresh==='never')continue;let point=null;for(let i=0;i<30;i++){const angle=g.rng()*Math.PI*2,r=25+g.rng()*85,q={x:a[1]+Math.cos(angle)*r,y:a[2]+Math.sin(angle)*r};if(!inside(q,group?.bounds)||distance(q,g.p)<175||g.blocked(q.x,q.y,false)||!g.clearLine({x:a[1],y:a[2]},q,false)||m.npcs.some(n=>distance(n,q)<110)||st.enemies.some(e=>e!==old&&!e.dead&&distance(e,q)<35))continue;point=q;break;}if(!point){const q={x:a[1],y:a[2]};if(!g.blocked(q.x,q.y,false)&&distance(q,g.p)>=175)point=q;}if(!point)continue;const fresh=g.enemy(a[0],point.x,point.y,key);attachGroup(m,fresh);if(old)Object.assign(old,fresh);else st.enemies.push(fresh);}for(const p of st.props){const base=m.props.find(v=>v.id===p.id);if(!base||p.secret||p.id.startsWith('v9-'))continue;const renewable=!p.action&&['crate','barrel','pot'].includes(p.type)||p.action==='herb';if(renewable&&(p.used||p.broken)&&g.rng()<(p.action==='herb'?.45:.35)){p.used=false;p.broken=false;p.hp=p.action?999:18;}}st.lastRefresh=g.time;}
export function saveBlockV9(g){if(!g)return '没有正在进行的旅程。';const boss=g.enemies?.some(e=>!e.dead&&uniqueEnemy(e));if(boss||(g.map==='canal'&&g.chapter===3)||(g.map==='chapel'&&g.chapter===3)||(g.map==='manor'&&g.chapter>=8&&g.chapter<10))return '封闭战斗期间无法保存或导出。战斗前的记录仍然保留。';return '';}
export function doorTransitionV9(g,d){const warning=(title,body)=>({id:'door:'+g.map+':'+d.to,title,body,to:d.to,x:d.tx,y:d.ty});if(d.to==='chapel'&&g.chapter===2)return warning('礼拜厅内','进去后会发生刺杀与突围，暂时无法返回街区。战斗期间不能保存。请先整理装备和药品。');if(d.to==='canal'&&!g.flags.captainDefeated&&g.chapter===3)return warning('闸口的盾声','前方是追缉官把守的闸口。进入后需击败他才能通过，战斗期间不能保存。');if(d.to==='echo'&&!g.flags.echoWardenDefeated)return warning('旧机房深处','里面有一头守着机器的兽。战斗期间不能保存；退路仍可使用。');if(d.to==='wellcrypt'&&!g.flags.v9WardenDefeated)return warning('井壁下的踏孔','下方的护井兽会堵住退路。击败它之前不能离开或保存；这处石室可以暂时不探。');return null;}
export function propTransitionV9(g,id){if(id==='inner-door'&&g.chapter===7)return {id:'manor-alarm',title:'庄园内门',body:'靠近内门会推进委托，随后暂时无法回到灰桥和驿站。接下来的封闭战斗期间不能保存。还有想调查的地方，可以先去。',prop:id};if(['exile-mark','exile-deep'].includes(id)&&g.chapter===10)return exileTransitionV9();return null;}
export function exileTransitionV9(){return {id:'exile-crossing',title:'界碑后的雾',body:'跨过界碑，暂时无法回到泄水沟、庄园与驿站。未完成的探索会留在身后。要继续往雾里走吗？',scene:'ch2ExileApproach',then:'ch2_cross'};}
export function sortNPCOptionsV9(g,id,options){const goal=g.objective(),main={steward:g.ready('rats')?'ratsDone':'ratsAccept',sister:'contractAccept',watch:'pass',seline:'ch2:relay'};const readyActions=new Set(['oilDone','letterDone','herbsMira','herbsWoman','oldReturn','lanternReturn','echoReturn','ch2:pump-reward']);const taskActions=new Set(['ratsAccept','oilAccept','letterAccept','herbsAccept','lanternAccept','echoAccept','ch2:pump','ch2:relay']);const score=v=>{if(goal.map===g.map&&goal.target===id&&(v.action===main[id]||id==='seline'&&/relay/.test(v.action)))return 0;if(readyActions.has(v.action))return 1;if(taskActions.has(v.action))return 2;if(/Progress|Progress|Verify|Unclear|workState|WorkState|pump/.test(v.action))return 3;return 4;};return options.map((v,i)=>({...v,_order:i})).sort((a,b)=>score(a)-score(b)||a._order-b._order).map(({_order,...v})=>v);}
export function updateCompanionV9(g,dt){const a=g.saint;if(g.chapter<3||g.pending||['chapel','wellcrypt'].includes(g.map)){a.visible=false;a.moving=false;a.clearFor=0;return;}const local=g.enemies.some(e=>!e.dead&&(distance(e,g.p)<280&&g.clearLine(e,g.p,false)||['COMBAT','ALERT'].includes(e.aiState)&&distance(e,g.p)<550));if(local){a.visible=false;a.moving=false;a.clearFor=0;a.path=null;return;}a.clearFor=(a.clearFor||0)+dt;if(a.clearFor<1.4)return;let goal=null;for(const offset of [Math.PI,Math.PI*.65,-Math.PI*.65,Math.PI*.35,-Math.PI*.35,0]){const q={x:g.p.x+Math.cos(g.p.angle+offset)*112,y:g.p.y+Math.sin(g.p.angle+offset)*112};if(!g.blocked(q.x,q.y)&&g.clearLine(q,g.p,false)&&!g.npcs.some(n=>distance(n,q)<50)){goal=q;break;}}if(!goal)return;if(!a.visible||distance(a,g.p)>300){if(distance(goal,g.p)<58||!g.clearLine(goal,g.p,false))return;a.x=goal.x;a.y=goal.y;a.visible=true;a.moving=false;a.appear=.25;a.path=null;a.timer=0;}a.appear=Math.max(0,(a.appear||0)-dt);a.moving=false;a.timer=(a.timer||0)-dt;if(distance(a,g.p)<66){const dx=a.x-g.p.x,dy=a.y-g.p.y,d=Math.max(1,Math.hypot(dx,dy));g.moveActor(a,a.x+dx/d*70*dt,a.y+dy/d*70*dt);return;}if(distance(a,goal)<38)return;if(a.timer<=0){a.path=g.routeTo(goal,a);a.timer=.6;}while(a.path?.length&&distance(a,a.path[0])<13)a.path.shift();const n=a.path?.[0];if(n){const d=Math.max(1,distance(a,n)),travel=Math.min(d,185*dt);a.angle=Math.atan2(n.y-a.y,n.x-a.x);g.moveActor(a,a.x+(n.x-a.x)/d*travel,a.y+(n.y-a.y)/d*travel);a.walkDistance=(a.walkDistance||0)+travel;a.anim=(a.anim||0)+travel/18;}}
