#!/usr/bin/env python3
"""Compile only explicitly selected spoken rows from the adopted chapter manuscript."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
script = (ROOT / 'docs/harness/CHAPTER_01.md').read_text()

def part(start, end):
    return script.split(start, 1)[1].split(end, 1)[0]

def rows(text):
    result = []
    for line in text.splitlines():
        m = re.match(r'^(奥伦|诺恩|薇蕾娜|鲁恩|阿林|托马|朵莉|艾莉娅|卡德兰|勤务人员|巡卫|追缉官|塞琳|年轻助手|老人|来人|女性|年轻人|军吏)：(.+)$', line)
        if m:
            spoken = re.sub(r'^（[^）]*）', '', m[2]).strip()
            if spoken:
                result.append([m[1], spoken])
    return result

selected = {
    'c1Intro': ('### 01 ', '完成支线：'),
    'c1RatDone': ('完成支线：', '### 02 '),
    'c1Contract': ('### 02 ', '### 03 '),
    'c1Receipt': ('### 03 ', '### 04 '),
    'c1CourierAccept': ('### 04 ', '还信后：'),
    'c1CourierDone': ('还信后：', '### 05 '),
    'c1Watch': ('### 05 ', '朵莉可选交谈：'),
    'c1Dolly': ('朵莉可选交谈：', '米拉支线：'),
    'c1Morning': ('### 06 ', '### 07 '),
    'c1Recon': ('### 07 ', '### 08 '),
    'c1Murder': ('#### 08A ', '#### 08B '),
    'c1Rescue': ('#### 08B ', '#### 08C '),
    'c1Confront': ('#### 08C ', '此处恢复玩家控制。'),
    'c1Seal': ('#### 08D ', '### 09 '),
    'c1Alley': ('### 09 ', '第一处岔口'),
    'c1AlleyCry': ('第一处岔口', '### 10 '),
    'c1Canal': ('### 10 ', '真实战斗恢复。'),
    'c1Bandage': ('战后玩家手动转绞盘。', '### 11 '),
    'c1RoadTerms': ('### 11 ', '诺恩从行动补给袋'),
    'c1Cloak': ('诺恩从行动补给袋', '### 12 '),
    'c1Station': ('### 12 ', '## 章尾未知人物'),
    'c1ShadowOld': ('**同日，地点未明。老人', '**当夜，地点未明。修长女性'),
    'c1ShadowWoman': ('**当夜，地点未明。修长女性', '**次日，北方前哨。好战年轻人'),
    'c1ShadowYoung': ('**次日，北方前哨。好战年轻人', '幕后尾声可标注'),
}
dialogues = {key: rows(part(*span)) for key, span in selected.items()}
dialogues.update({
    'c1Dossier': [['薇蕾娜','三名成年工女经施济院转送主祭私院后失踪。旧册记为外地投亲，家属否认。两份证词与后院出入记录互相对应。'],['诺恩','我带画像。原件留在这里。']],
    'c1Pass': [['鲁恩','通行纸右边缺角，内侧一道细线。回执有两道印，别跟货单放在一起。']],
    'c1Route': [['薇蕾娜','从东准备室后门撤。过水渠北闸，去灰石驿站。别走正城门。']],
    'c1Supply': [['艾莉娅','水先给坐着的老人。让队伍往棚里移，别淋到伤口。'],['修女','我去请医师。您把这卷干净布带进去。']],
    'c1Missing': [['旁白','寻人页上两笔“已返家”被墨线划去，旁边补着家属的否认。另有车夫留下的口信：失踪当晚，一辆带施济后院通行记号的车出了城。'],['诺恩','记号和日期。先记下。']],
    'c1CareRoom': [['勤务人员','干净布在床边，热水放窗下。担架从南边这条道抬，别堵门。']],
    'c1Latch': [['诺恩','新换的门闩，里面能开。外廊通小巷。']],
    'c1StartConfirm': [['诺恩','目标已确认。东侧退路通着。']],
    'c1Captured': [['艾莉娅','把他的手扣住。刀收起来，别再伤人。'],['巡卫','医师已经进来了。']],
    'c1GateClosed': [['诺恩','先让追缉官离开闸机。绞盘在东岸。']],
    'c1Cart': [['诺恩','车是空的。从这道墙缝过去。'],['艾莉娅','我自己走。别拉我的手。']],
    'c1Return': [['诺恩','检修道通旧王道。城北还在封街，只能避开岗哨。'],['艾莉娅','我记得这条路。你别以为我不想回去。']],
    'c1Rest': [['塞琳','炉边能坐，热水也有。要床铺得付二十金；巡卫若来查验，我留不住你们。'],['艾莉娅','我坐门边。']],
    'c1End': [['旁白','午钟之前 · 第一章终'],['艾莉娅','纸给我。我还没有写完。']],
    'c1HerbDelivery': [['米拉','先把这份药送给蕾娜。银叶草留下，我现在配。报酬给你留着。'],['诺恩','南街那家。']],
    'c1MedicineGiven': [['蕾娜','是米拉配的？太好了，他刚刚又烧起来了。'],['诺恩','按她写的用。']],
    'c1ReturnReward': [['米拉','药送到了？这是你的报酬。']],
})
assert all(dialogues.values())
(ROOT / 'dist/ch1-script-v31.js').write_text('// Generated by tools/build_ch1_script.py from CHAPTER_01 0.2. Author-only prose is excluded.\nexport const C1_DIALOGUES='+json.dumps(dialogues,ensure_ascii=False,indent=1)+';\n')
print(f'{len(dialogues)} scenes, {sum(map(len,dialogues.values()))} spoken rows')
